module.exports = {
  type: 'category',
  label: 'FAQs',
  link: {
    type: 'doc',
    id: 'supporting-pages/faqs/faq',
  },
  items: [
    'supporting-pages/faqs/add-logo-image-text',
    'supporting-pages/faqs/dashboard-navigation',
    'supporting-pages/faqs/delete-interface',
    'supporting-pages/faqs/drag-trends-chrome',
    'supporting-pages/faqs/find-expiration-date',
    'supporting-pages/faqs/get-hash-values',
    'supporting-pages/faqs/hide-navigation-menu',
    'supporting-pages/faqs/missing-toolbar',
    'supporting-pages/faqs/opc-interface-support',
    'supporting-pages/faqs/override-kpi-status',
    'supporting-pages/faqs/ports-for-firewall',
    'supporting-pages/faqs/print-save-pdf',
    'supporting-pages/faqs/remove-hash-symbol',
    'supporting-pages/faqs/search-fields-attributes',
    'supporting-pages/faqs/send-alerts-office365',
    'supporting-pages/faqs/set-asset-status',
    'supporting-pages/faqs/share-dashboard',
    'supporting-pages/faqs/share-dashboard',
    'supporting-pages/faqs/use-olap-interface',
    'supporting-pages/faqs/why-license-key-error'
  ],
}