/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  docs: [
    {
      type: 'doc',
      id: 'what-is-visual-kpi',
      // label: 'What is Visual KPI',
      // className: '',
    },
    {
      type: 'doc',
      id: 'how-visual-kpi-works',
      // label: 'How Visual KPI Works',
      // className: '',
    },
    {
      type: 'doc',
      id: 'how-to-use-the-documentation',
      // label: 'How to Use the Documentation',
      // className: '',
    },
    {
      type: 'doc',
      id: 'glossary',
      label: 'Glossary',
      // className: '',
    },
    {
      type: 'category',
      label: "Get Started",
      // className: '',
      link: {
        type: 'doc',
        id: 'get-started/overview',
      },
      items: [
        'get-started/visual-kpi-core-concepts',
        'get-started/ways-to-use-visual-kpi',
        'get-started/objects',
        'get-started/navigation',
        'get-started/data-update-and-timestamp',
        'get-started/notifications',
        'get-started/access-level'
      ],
    },
    {
      type: 'category',
      label: "Viewers",
      // className: '',
      link: {
        type: 'doc',
        id: 'viewers/overview',
      },
      items: [
        'viewers/navigation',
        {
          type: 'category',
          label: "KPI Trends",
          // className: '',
          link: {
            type: 'doc',
            id: 'viewers/kpi-trends/kpi-trends',
          },
          items: [
            'viewers/kpi-trends/view-options',
            'viewers/kpi-trends/trend-comments',
          ],
        },
        'viewers/charts',
        'viewers/tables',
        {
          type: 'category',
          label: "Dashboard",
          // className: '',
          link: {
            type: 'doc',
            id: 'viewers/dashboard/dashboard',
          },
          items: [
            'viewers/dashboard/share-dashboard',
          ],
        },
        'viewers/groups-hierarchy',
        'viewers/search-tool',
        {
          type: 'category',
          label: "Visualization options",
          // className: '',
          link: {
            type: 'doc',
            id: 'viewers/visualization-options/visualization-options',
          },
          items: [
            {
              type: 'category',
              label: "Charts visualizations",
              // className: '',
              link: {
                type: 'doc',
                id: 'viewers/visualization-options/charts-visualizations/charts-visualizations',
              },
              items: [
                
              ],
            },  
            {
              type: 'category',
              label: "KPI visualizations",
              // className: '',
              link: {
                type: 'doc',
                id: 'viewers/visualization-options/kpi-visualizations/kpi-visualizations',
              },
              items: [
                
              ],
            },  
          ],
        },
        'viewers/time-range',
        'viewers/ad-hoc-view',
        'viewers/analytics-tools',
        'viewers/alerts',
        'viewers/bookmarks', 
        {
          type: 'category',
          label: "Use Cases",
          // className: '',
          link: {
            type: 'doc',
            id: 'viewers/use-cases/use-cases',
          },
          items: [
          ],
        },
        {
          type: 'category',
          label: "Best Practices",
          // className: '',
          link: {
            type: 'doc',
            id: 'viewers/best-practices/best-practices',
          },
          items: [
          ],
        },
      ],
    },
    
    // {
    //   type: 'html',
    //   value: "<span class='sidebar-title'>ARTICLES</span>",
    //   defaultStyle: true,
    // },
    // {
    //   type: 'doc',
    //   id: 'working-with-kpi-trends',
    //   label: 'Working with KPI Trends',
    //   // className: '',
    // }
  ],
   
};

module.exports = sidebars;
