/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const { 
  gettingStarted,
  setupAdm,
  designer,
  endUser,
  referenceGuides,
  supportingPages,
  tcalc 
} = require('./.sidebar');

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  docs: [
    {
      type: 'html',
      value: '<span class=\'sidebar_title\'>Getting Started</span>',
      defaultStyle: true,
      className: 'sidebar_title',
    },
    ...gettingStarted,
    {
      type: 'html',
      value: '<span class=\'sidebar_title\'>Setup and Administration</span>',
      defaultStyle: true,
      className: 'sidebar_title',
    },
    ...setupAdm,
    {
      type: 'html',
      value: '<span class=\'sidebar_title\'>Visual KPI Designer</span>',
      defaultStyle: true,
      className: 'sidebar_title',
    },
    ...designer,
    {
      type: 'html',
      value: '<span class=\'sidebar_title\'>End User</span>',
      defaultStyle: true,
      className: 'sidebar_title',
    },
    ...endUser,
    {
      type: 'html',
      value: '<span class=\'sidebar_title\'>Reference Guides</span>',
      defaultStyle: true,
      className: 'sidebar_title',
    },
    ...referenceGuides,
    {
      type: 'html',
      value: '<span class=\'sidebar_title\'>Supporting Pages</span>',
      defaultStyle: true,
      className: 'sidebar_title',
    },
    ...supportingPages,
  ],
};

module.exports = sidebars;